.\" Process this file with
.\" groff -man -Tascii 2048tty.6
.\"
.TH 2048TTY 6 "FEBRUARY 2015"
.SH NAME
2048tty \- an implementation of 2048 in the terminal
.SH SYNOPSIS
.B 2048tty [-h] [-A
.I rate
.B | --animrate
.I rate
.B ]

.SH DESCRIPTION
.B 2048tty
is an implementation of Gabriele Cirulli's "2048" using Python and curses. It
uses 
.BR vim (1)
style keys to control the tiles.
The game consists of a four-by-four grid, each cell holding a number. The
object of the game is to merge tiles until a 2048 tile is produced.
Pressing '!' or 'd' will activate pdb or the
debug mode, respectively. To get out of pdb, type 'c' and press enter. To get
out of debug mode, simply press 'd' a second time.
.SH OPTIONS
.IP -h
Print useful help information.
.IP "-A --animrate"
Sets to delay between animation ticks, in seconds. The default is 0.009. Note
that the number must be stuck to the end of the option, not seperated by a
space.
.SH FILES
.I ~/.2048tty
.RS
Default file where the high score and in-progress games are saved. If it does
not exists, it will be created automatically. JSON format.
.SH ENVIRONMENT
.IP 2048TTY_FILE
If non-null the path that will be used in place of
.I ~/.2048tty
\.
.SH BUGS
The current score is not saved with the rest of the game. Specifically, if
you restart the game, the tiles will be preserved, but your current score will
reset to zero.
.SH AUTHOR
Samuel Phillips <samuel.phillips29 at gmail dot com>
